### ISSUE TITLE
Função get_data com kwargs

### ISSUE THREAD

**Issue by im-alexandre** [TeoCalvo/Dotabricks#5]
Na função get_data, não é necessário incluir os parâmetros na unha. Podemos tentar o seguinte código:
```python
def get_data(**kwargs):
    """docstring for get_data"""
    url = "https://api.opendota.com/api/proMathces"
    response = requests.get(url, params=kwargs)
    return response.json()
```
Não muda nada no exemplo, mas fica como dica p galera.

**Comment by TeoCalvo** [comment]
Animal! Valeu demais pela dica! :D

**Comment by TeoCalvo** [comment]
Vou fechar, dado que realizamos o merge com o código refatorado.
